stages:
  # # to run a step always use without deps and outs
  # always_run:
  #   cmd: python -c "print('hello')"
  load_data:
    cmd: python src/stage_01_load_save.py -c config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
  
  split_data:
    cmd: python src/stage_02_split_data.py -c config/config.yaml -p params.yaml
    deps:
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/raw_local_dir/data.csv
    # we can also define dependency for individual parameter in params.yaml
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv
  
  train_model:
    cmd: python src/stage_03_train.py -c config/config.yaml -p params.yaml
    deps:
      - src/stage_03_train.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv
    params:
      - model_params.ElasticNet.alpha
      - model_params.ElasticNet.l1_ratio
      - model_params.ElasticNet.random_state
    outs:
      - artifacts/model_dir/ElasticNet.pkl
    