# Configure the paths and filename
data_source: http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv
  split_data_dir: split_data_dir
  train_file: train.csv
  test_file: test.csv
